from . import museo_model
from . import objeto_model
from . import historia_barrio_model
from . import convenio_model
from . import actividad_model
from . import informe_model
from . import registro_asistencia_model
from . import configuracion_model 
from . import wizard_models
from . import res_partner
from . import museo_galeria_model
from . import reporte_model
from . import acciones_reportes
from . import wizard_reportes
